[build]
  publish = "public/"
  command = "npm run build"

[build.processing]
  skip_processing = true

[build.environment]
  NODE_VERSION = "18.12.1"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# https://answers.netlify.com/t/serve-a-serverless-function-from-root/47275/2
[[redirects]]
  from = "/artists/"
  to = "/.netlify/functions/artists"
  status = 200
  force = true